-- ===========================================================================
--  V1 — Esquema inicial
--  Sistema de registro de vacaciones, citas médicas y permisos
--
--  REGLA CENTRAL DEL SISTEMA:
--  Todo el tiempo se guarda en MINUTOS, como número entero. Jamás en días
--  decimales ni en números con coma. Los "días" son solo una forma de MOSTRAR
--  esos minutos, usando el parámetro horas_por_jornada:
--
--      minutos_por_dia = horas_por_jornada * 60      (por defecto 8 * 60 = 480)
--      dias            = minutos / minutos_por_dia   (división entera)
--      horas_sueltas   = (minutos % minutos_por_dia) / 60
--
--  Con enteros, sumar y restar siempre da exacto. Con decimales, 8.75 días
--  termina siendo 8.749999999998 después de varias operaciones, y eso en un
--  registro laboral se convierte en un reclamo.
-- ===========================================================================


-- ===========================================================================
--  usuario — las personas que ENTRAN al sistema.
--  No confundir con "empleado": un empleado es alguien de quien se lleva el
--  control de vacaciones, y normalmente NO tiene acceso a la aplicación.
-- ===========================================================================
CREATE TABLE usuario (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              VARCHAR(50)  NOT NULL,
    password_hash         VARCHAR(100) NOT NULL,
    nombre_completo       VARCHAR(150) NOT NULL,
    rol                   VARCHAR(20)  NOT NULL DEFAULT 'ADMIN',
    activo                BOOLEAN      NOT NULL DEFAULT TRUE,
    debe_cambiar_password BOOLEAN      NOT NULL DEFAULT TRUE,
    intentos_fallidos     INTEGER      NOT NULL DEFAULT 0,
    bloqueado_hasta       TIMESTAMPTZ,
    ultimo_login          TIMESTAMPTZ,
    creado_en             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    creado_por            BIGINT,

    CONSTRAINT uk_usuario_username    UNIQUE (username),
    CONSTRAINT ck_usuario_rol         CHECK (rol IN ('ADMIN')),
    CONSTRAINT ck_usuario_intentos    CHECK (intentos_fallidos >= 0),
    CONSTRAINT fk_usuario_creado_por  FOREIGN KEY (creado_por) REFERENCES usuario (id)
);

COMMENT ON TABLE  usuario                       IS 'Personas con acceso al sistema.';
COMMENT ON COLUMN usuario.username              IS 'Se guarda siempre en minúsculas para que "Brenda" y "brenda" sean el mismo usuario.';
COMMENT ON COLUMN usuario.password_hash         IS 'Hash BCrypt (costo 12). Nunca la contraseña en texto plano.';
COMMENT ON COLUMN usuario.rol                   IS 'Hoy solo existe ADMIN. La columna queda para poder agregar otro rol sin migrar la tabla.';
COMMENT ON COLUMN usuario.debe_cambiar_password IS 'TRUE obliga a cambiar la contraseña antes de usar cualquier otra pantalla.';
COMMENT ON COLUMN usuario.bloqueado_hasta       IS 'Si tiene fecha y es futura, el usuario no puede entrar (bloqueo por intentos fallidos).';
COMMENT ON COLUMN usuario.creado_por            IS 'Qué usuario lo creó. NULL en el administrador inicial, porque lo crea el sistema.';


-- ===========================================================================
--  empleado — los trabajadores de los que se lleva el control.
--  Nunca se borran: se dan de baja (activo = FALSE) para no perder historial.
-- ===========================================================================
CREATE TABLE empleado (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo          VARCHAR(150) NOT NULL,
    cargo                    VARCHAR(100),
    area_o_dependencia       VARCHAR(100),
    fecha_ingreso            DATE,
    saldo_vacaciones_minutos INTEGER      NOT NULL DEFAULT 0,
    activo                   BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en                TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_en           TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_empleado_activo ON empleado (activo);
CREATE INDEX ix_empleado_nombre ON empleado (lower(nombre_completo));

COMMENT ON TABLE  empleado                          IS 'Trabajadores registrados. No son usuarios del sistema.';
COMMENT ON COLUMN empleado.saldo_vacaciones_minutos IS 'SALDO ÚNICO en minutos. A pesar del nombre, de acá descuentan los tres tipos: vacaciones, citas médicas y permisos. Puede quedar negativo solo si un ADMIN lo autoriza expresamente.';
COMMENT ON COLUMN empleado.activo                   IS 'FALSE = dado de baja. Nunca se borra la fila: el historial no se puede perder.';


-- ===========================================================================
--  solicitud — cada vacación, cita médica o permiso que Brenda anota.
--  Esto es un REGISTRO, no un flujo de aprobación: el permiso ya fue
--  autorizado fuera del sistema. Por eso solo hay dos estados.
-- ===========================================================================
CREATE TABLE solicitud (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id         BIGINT       NOT NULL,
    tipo                VARCHAR(20)  NOT NULL,
    fecha_inicio        DATE         NOT NULL,
    fecha_fin           DATE         NOT NULL,
    minutos_solicitados INTEGER      NOT NULL,
    motivo              VARCHAR(300),
    estado              VARCHAR(20)  NOT NULL DEFAULT 'REGISTRADA',
    registrado_por      BIGINT       NOT NULL,
    creado_en           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    anulado_en          TIMESTAMPTZ,
    anulado_por         BIGINT,
    motivo_anulacion    VARCHAR(300),

    CONSTRAINT fk_solicitud_empleado       FOREIGN KEY (empleado_id)    REFERENCES empleado (id),
    CONSTRAINT fk_solicitud_registrado_por FOREIGN KEY (registrado_por) REFERENCES usuario (id),
    CONSTRAINT fk_solicitud_anulado_por    FOREIGN KEY (anulado_por)    REFERENCES usuario (id),
    CONSTRAINT ck_solicitud_tipo    CHECK (tipo   IN ('VACACIONES', 'CITA_MEDICA', 'PERMISO')),
    CONSTRAINT ck_solicitud_estado  CHECK (estado IN ('REGISTRADA', 'ANULADA')),
    CONSTRAINT ck_solicitud_minutos CHECK (minutos_solicitados > 0),
    CONSTRAINT ck_solicitud_fechas  CHECK (fecha_fin >= fecha_inicio),
    -- Una solicitud anulada SIEMPRE tiene fecha, responsable y motivo de
    -- anulación; una registrada NUNCA los tiene. La base de datos no permite
    -- un estado a medias, aunque el código tuviera un error.
    CONSTRAINT ck_solicitud_anulacion CHECK (
        (estado = 'REGISTRADA' AND anulado_en IS NULL     AND anulado_por IS NULL     AND motivo_anulacion IS NULL)
     OR (estado = 'ANULADA'    AND anulado_en IS NOT NULL AND anulado_por IS NOT NULL AND motivo_anulacion IS NOT NULL)
    )
);

CREATE INDEX ix_solicitud_empleado ON solicitud (empleado_id);
CREATE INDEX ix_solicitud_fechas   ON solicitud (fecha_inicio, fecha_fin);
CREATE INDEX ix_solicitud_estado   ON solicitud (estado);

COMMENT ON COLUMN solicitud.tipo                IS 'No cambia el cálculo: los tres descuentan igual. Sirve para desglosar los reportes.';
COMMENT ON COLUMN solicitud.minutos_solicitados IS 'Tiempo en minutos. Lo escribe la usuaria en días u horas y el sistema lo convierte.';
COMMENT ON COLUMN solicitud.motivo              IS 'Texto corto y opcional. En citas médicas NUNCA debe contener información médica.';
COMMENT ON COLUMN solicitud.estado              IS 'REGISTRADA o ANULADA. No existen "pendiente", "aprobada" ni "rechazada": esto es un registro, no un trámite.';


-- ===========================================================================
--  movimiento_saldo — el libro contable del saldo.
--  Cada cambio del saldo de un empleado deja su renglón acá. El saldo de la
--  tabla empleado nunca se modifica sin escribir también su movimiento, así
--  que siempre se puede reconstruir la historia completa.
-- ===========================================================================
CREATE TABLE movimiento_saldo (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empleado_id              BIGINT       NOT NULL,
    solicitud_id             BIGINT,
    tipo_movimiento          VARCHAR(20)  NOT NULL,
    minutos                  INTEGER      NOT NULL,
    saldo_resultante_minutos INTEGER      NOT NULL,
    descripcion              VARCHAR(300),
    realizado_por            BIGINT       NOT NULL,
    creado_en                TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_movimiento_empleado      FOREIGN KEY (empleado_id)   REFERENCES empleado (id),
    CONSTRAINT fk_movimiento_solicitud     FOREIGN KEY (solicitud_id)  REFERENCES solicitud (id),
    CONSTRAINT fk_movimiento_realizado_por FOREIGN KEY (realizado_por) REFERENCES usuario (id),
    CONSTRAINT ck_movimiento_tipo CHECK (
        tipo_movimiento IN ('SALDO_INICIAL', 'AJUSTE_MANUAL', 'CONSUMO', 'REVERSION')
    ),
    CONSTRAINT ck_movimiento_minutos CHECK (minutos <> 0)
);

CREATE INDEX ix_movimiento_empleado ON movimiento_saldo (empleado_id, creado_en DESC);

COMMENT ON COLUMN movimiento_saldo.minutos                  IS 'Positivo suma al saldo, negativo resta. Nunca cero.';
COMMENT ON COLUMN movimiento_saldo.saldo_resultante_minutos IS 'Cómo quedó el saldo DESPUÉS de este movimiento. Permite auditar sin recalcular todo.';
COMMENT ON COLUMN movimiento_saldo.solicitud_id             IS 'La solicitud que originó el movimiento. NULL en saldo inicial y ajustes manuales.';


-- ===========================================================================
--  auditoria — quién hizo qué, cuándo y desde dónde.
-- ===========================================================================
CREATE TABLE auditoria (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT,
    accion     VARCHAR(60)   NOT NULL,
    entidad    VARCHAR(40),
    entidad_id BIGINT,
    detalle    VARCHAR(1000),
    ip         VARCHAR(45),
    creado_en  TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX ix_auditoria_creado_en ON auditoria (creado_en DESC);
CREATE INDEX ix_auditoria_usuario   ON auditoria (usuario_id);

COMMENT ON COLUMN auditoria.usuario_id IS 'NULL cuando alguien intenta entrar con un usuario que no existe.';
COMMENT ON COLUMN auditoria.ip         IS 'Hasta 45 caracteres para que quepa una dirección IPv6.';


-- ===========================================================================
--  parametro — configuración editable desde la propia aplicación.
--  Nada de valores quemados en el código.
-- ===========================================================================
CREATE TABLE parametro (
    clave           VARCHAR(50) PRIMARY KEY,
    valor           VARCHAR(200) NOT NULL,
    descripcion     VARCHAR(300),
    actualizado_en  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_por BIGINT,

    CONSTRAINT fk_parametro_actualizado_por FOREIGN KEY (actualizado_por) REFERENCES usuario (id)
);

INSERT INTO parametro (clave, valor, descripcion) VALUES
    ('horas_por_jornada', '8',
     'Cuántas horas tiene una jornada laboral completa. Se usa para convertir minutos a días.'),
    ('zona_horaria', 'America/Managua',
     'Zona horaria para mostrar fechas, horas y calcular el saludo del tablero.');
